language: python
python:
  - "2.7"



# command to install dependencies
install:
  - pip install jupyter pytest
  - pip install .

# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below

