language: python
python:
  - "2.7"

install:
  - pip install jupyter pytest
  - pip install nose coverage
  - pip install coveralls
  - pip install pytest-cov pytest-pep8
  - pip install .

before_script:
  - py.test --cov=dict2uml

script:
  - python setup.py nosetests --with-coverage --cover-package pypiview
  - py.test --doctest-modules --pep8 dict2uml -v --cov dict2uml --cov-report term-missing # or py.test for Python versions 3.5 and below

after_success:
  - coveralls